### ISSUE TITLE
image embedding of FB15K-DB15K-YG15K

### ISSUE THREAD

**Issue by ninibymilk** [blzhu0823/PathFusion#1]
can you provide the image embedding of FB15K-DB15K-YG15K?

**Comment by blzhu0823** [comment]
Sorry for keeping you waiting for so long, image embedding of DB15K, FB15K, YAGO15K, and their adjacency matrix from entity Id to image Id have been uploaded [here](https://drive.google.com/file/d/1Yn4XciN_y2m17_NunVmHwWh79UUjiNoI/view?usp=sharing)
