### ISSUE TITLE
在DB15K-FB15K数据集上的部分初始化代码

### ISSUE THREAD

**Issue by SunnyCc123** [blzhu0823/PathFusion#2]
Hello, I noticed that when running MSP_Attr.py, you initialised source2attr and target2attr to zero matrix but did not update the matrix values, which resulted in the result also being a zero matrix when performing matrix concatenation operation to calculate source2target. By running the code, I end up with Hits@1, Hits@10, and MRR all converging to 0. Can you tell me if the initialisation was done in a wrong way or something was missed?

**Comment by blzhu0823** [comment]
Thanks, I've fixed this bug in utils_db.py and utils_yb.py.
